### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ankit-fueled** [sambhav-fueled/swift-style-guide#4]
- [x] Spacing between colon, data type and var name .. 
According to me, it should be like this 
var a: String
- [x] Position of Static variable and functions inside a class to be defined.
- [x] If you want to include argument name which is same as param name for first param.
Use

```  
func convert(#point: Point, toView view: View) -> Point 
```

Instead of 

```
func convert(point point: Point, toView view: View) -> Point  
```

**Comment by sambhav-fueled** [comment]
we need to use func convert(point point: Point, toView view: View) -> Point from swift 2.0 onwards, as there is no func convert(#point: Point, toView view: View) -> Point
